version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test

    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/frontend
      - ./frontend/node_modules

  backend:
    build: ./server
    container_name: backend
    ports:
      - "5001:5001"
    volumes:
      - ./server:/backend
      - ./backend/node_modules
