version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pizzastore

    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports:
      - "5425:5432"

    

  frontend:
    build:
      context: ./client
    container_name: frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/frontend
      - ./frontend/node_modules

    depends_on:
      - db

  backend:
    build:
      context: ./server
    container_name: backend_app
    ports:
      - "5001:5001"
    volumes:
      - ./server:/backend
      - ./backend/node_modules
    
    depends_on:
      - db
