version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pizzastore

    volumes:
      - ./pgdata:/var/lib/postgresql/data

    ports:
      - "5425:5432"

  frontend:
    build: ./client
    container_name: frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./client:/frontend_app
      - ./frontend_app/node_modules

  backend:
    build: ./server
    container_name: backend_app
    ports:
      - "5001:5001"
    volumes:
      - ./server:/backend_app
      - ./backend_app/node_modules
